const CLASS_NAME_OVERRIDES = {
  "SafetyCar": "Safety Car",
  "ARC_Cam": "ARC Camaro",
  "Cat620R": "Caterham 620R",
  "Cat_Academy": "Caterham Academy",
  "Cat_Superlight": "Caterham Superlight",
  "Cat_Supersport": "Caterham Supersport",
  "CopaClassicFL": "Copa Classic FL",
  "CopaClassicB": "Copa Classic B",
  "CopaTruck": "Copa Truck",
  "CopaFusca": "Copa Fusca",
  "Montana": "Copa Montana",
  "CopaUno": "Copa Uno",
  "DPI": "DPI",
  "F-Hitech_Gen1": "F-Hitech Gen 1",
  "F-Hitech_Gen2": "F-Hitech Gen 2",
  "F-3": "Formula 3",
  "F-Classic_Gen1": "F-Classic Gen 1",
  "F-Classic_Gen2": "F-Classic Gen 2",
  "F-Classic_Gen3": "F-Classic Gen 3",
  "F-Classic_Gen4": "F-Classic Gen 4",
  "F-Dirt": "Formula Dirt",
  "FE-G1": "F-Edge",
  "F-Inter": "F-Inter",
  "F-Junior": "F-Junior",
  "F-Retro_Gen1": "F-Retro Gen 1",
  "F-Retro_Gen2": "F-Retro Gen 2",
  "F-Retro_Gen3": "F-Retro Gen 3",
  "F-Trainer": "F-Trainer",
  "F-Trainer_A": "F-Trainer Advanced",
  "F-Ultimate_Gen1": "F-Ultimate Gen 1",
  "F-Ultimate_Gen2": "F-Ultimate Gen 2",
  "F-Ultimate": "F-Ultimate",
  "F-USA_2023": "F-USA 2023",
  "F-USA_Gen1": "F-USA Gen 1",
  "F-USA_Gen2": "F-USA Gen 2",
  "F-USA_Gen3": "F-USA Gen 3",
  "F-V10_Gen1": "F-V10 Gen 1",
  "F-V10_Gen2": "F-V10 Gen 2",
  "F-V10_Gen3": "F-V10 Gen 3",
  "F-V8_Gen1": "F-V8 Gen 1",
  "F-V8_Gen2": "F-V8 Gen 2",
  "F-Reiza": "F-V8 Gen 3",
  "F-Vee": "F-Vee",
  "F-Vee_Gen2": "F-Vee Gen 2",
  "F-Vintage_Gen1": "F-Vintage Gen 1",
  "F-Vintage_Gen2": "F-Vintage Gen 2",
  "G40Cup": "G40 Cup",
  "G55Supercup": "G55 Supercup",
  "Group A": "Group A",
  "Group C": "Group C",
  "TC70S": "GT Classics",
  "GTOpen": "GT Open",
  "GT1": "GT1",
  "GT1_05": "GT1 '05",
  "GT2_05": "GT2 '05",
  "GT3": "GT3",
  "GT3_Gen2": "GT3 Gen 2",
  "GT4": "GT4",
  "GT5": "GT5",
  "GTE": "GTE",
  "GTR_04": "GTR '04",
  "Hot Cars": "Hot Cars",
  "Hypercars": "Hypercars",
  "Kart125cc": "Kart 125cc",
  "KartGX390": "Kart GX390",
  "KartRental": "Kart Rental",
  "KartShifter": "Kart Shifter",
  "Kartcross": "Kartcross",
  "LancerCup": "Lancer Cup",
  "LES_2025": "Ligier Cup",
  "LMDh": "LMDh",
  "LMP1_05": "LMP1 '05",
  "LMP2_05": "LMP2 '05",
  "LMP2_Gen1": "LMP2 Gen 1",
  "LMP2": "LMP2",
  "MiniChallenge": "Mini Challenge",
  "OldStock": "Old Stock",
  "Opala79": "Opala '79",
  "Opala86": "Opala '86",
  "P1": "P1",
  "P1Gen2": "P1 Gen 2",
  "P2": "P2",
  "P3": "P3",
  "P4": "P4",
  "Carrera Cup": "Carrera Cup",
  "Procar": "M1 Procar",
  "RX": "Rallycross",
  "SprintRace": "Sprint Race",
  "StockCar99": "Stock Car '99",
  "StockCarV8": "Stock Car '19",
  "StockCarV8_2020": "StockCar '20",
  "StockCarV8_2021": "StockCar '21",
  "StockCarV8_2022": "StockCar '22",
  "StockCarV8_2023": "StockCar '23",
  "StockCarV8_2024": "StockCar '24",
  "Stock_USA_Gen1": "Stock USA Gen1",
  "Stock_USA_Gen2": "Stock USA Gen2",
  "Stock_USA_Gen3": "Stock USA Gen3",
  "Stock_USA_Gen3_LM": "Stock USA Gen3 LM",
  "Street": "Street",
  "STT": "Trophy Trucks",
  "Super Trofeo": "Super Trofeo",
  "S96T": "Diablo Trofeo",
  "SuperV8": "Super V8",
  "Supercars": "Super Cars",
  "SuperKart": "Super Kart",
  "TSICup": "TSI Cup",
  "TC60S": "Vintage Tier 1",
  "TC60S2": "Vintage Tier 2",
};

const CLASS_COLORS = {
  "SafetyCar": "#fffb00",
  "ARC_Cam": "#f4ce25",
  "Cat620R": "#85ce26",
  "Cat_Academy": "#85ce26",
  "Cat_Superlight": "#85ce26",
  "Cat_Supersport": "#85ce26",
  "CopaClassicFL": "#fcf300",
  "CopaClassicB": "#d8251c",
  "CopaTruck": "#ffe126",
  "CopaFusca": "#ae2e27",
  "Montana": "#ae8136",
  "CopaUno": "#f6f95d",
  "DPI": "#ed5a00",
  "F-Hitech_Gen1": "#40bbff",
  "F-Hitech_Gen2": "#c63232",
  "F-3": "#37a2d6",
  "F-Classic_Gen1": "#f50303",
  "F-Classic_Gen2": "#f50303",
  "F-Classic_Gen3": "#f50303",
  "F-Classic_Gen4": "#f50303",
  "F-Dirt": "#ef7625",
  "FE-G1": "#14be47",
  "F-Inter": "#e2141f",
  "F-Junior": "#334372",
  "F-Retro_Gen1": "#e19560",
  "F-Retro_Gen2": "#8e2a4e",
  "F-Retro_Gen3": "#456843",
  "F-Trainer": "#f0eb27",
  "F-Trainer_A": "#ce6e12",
  "F-Ultimate_Gen1": "#ff2727",
  "F-Ultimate_Gen2": "#0fa39e",
  "F-Ultimate": "#26a6ff",
  "F-USA_2023": "#d86c12",
  "F-USA_Gen1": "#000000",
  "F-USA_Gen2": "#26bc7e",
  "F-USA_Gen3": "#e0222f",
  "F-V10_Gen1": "#005ce7",
  "F-V10_Gen2": "#dc2625",
  "F-V10_Gen3": "#ddbc17",
  "F-V8_Gen1": "#1e6fbd",
  "F-V8_Gen2": "#fec90a",
  "F-Reiza": "#da0014",
  "F-Vee": "#ec1c26",
  "F-Vee_Gen2": "#ed1c24",
  "F-Vintage_Gen1": "#227164",
  "F-Vintage_Gen2": "#8f1900",
  "G40Cup": "#f0800d",
  "G55Supercup": "#f0800d",
  "Group A": "#b9b9b9",
  "Group C": "#0a439c",
  "TC70S": "#999185",
  "GTOpen": "#d50000",
  "GT1": "#cdcdcd",
  "GT1_05": "#46d4f2",
  "GT2_05": "#f0ca19",
  "GT3": "#00a950",
  "GT3_Gen2": "#00a950",
  "GT4": "#5b616a",
  "GT5": "#3144e6",
  "GTE": "#ec0030",
  "GTR_04": "#9e9e9e",
  "Hot Cars": "#beb18a",
  "Hypercars": "#eaca62",
  "Kart125cc": "#2cb06e",
  "KartGX390": "#4adad9",
  "KartRental": "#f03232",
  "KartShifter": "#ec7034",
  "Kartcross": "#caae30",
  "LancerCup": "#da171b",
  "LES_2025": "#dcac03",
  "LMDh": "#3f4349",
  "LMP1_05": "#f22a3e",
  "LMP2_05": "#e5e25c",
  "LMP2_Gen1": "#3144e6",
  "LMP2": "#3852a4",
  "MiniChallenge": "#a8a8a8",
  "OldStock": "#ffcb06",
  "Opala79": "#8c4ab0",
  "Opala86": "#125ce0",
  "P1": "#c42323",
  "P1Gen2": "#c42323",
  "P2": "#bf9e14",
  "P3": "#1e1e1e",
  "P4": "#b946bc",
  "Carrera Cup": "#ce0a24",
  "Procar": "#353188",
  "RX": "#9dd000",
  "SprintRace": "#f51925",
  "StockCar99": "#e40a14",
  "StockCarV8": "#888888",
  "StockCarV8_2020": "#888888",
  "StockCarV8_2021": "#e6c156",
  "StockCarV8_2022": "#e6c156",
  "StockCarV8_2023": "#06a9eb",
  "StockCarV8_2024": "#06a9eb",
  "Stock_USA_Gen1": "#f93c20",
  "Stock_USA_Gen2": "#5ff3fd",
  "Stock_USA_Gen3": "#cfc72a",
  "Stock_USA_Gen3_LM": "#f52045",
  "Street": "#65d3d3",
  "STT": "#ef7d1c",
  "Super Trofeo": "#888888",
  "S96T": "#e42938",
  "SuperV8": "#ff2f25",
  "Supercars": "#c7c7c7",
  "SuperKart": "#0a61ce",
  "TSICup": "#001e50",
  "TC60S": "#df8826",
  "TC60S2": "#a2a2a1",
};

const DEFAULT_COLOR = "rgb(0, 98, 255)";

const CAR_LOGOS = {
  //Acura
  "Acura": "acura.png",
  //Alpine
  "Alpine": "alpine.png",
  //Aston Martin
  "Aston": "aston_martin.png",
  //Audi
  "Audi": "audi.png",
  //BMw
  "BMW": "bmw.png",
  //Brabham
  "Brabham": "brabham.png",
  //Cadillac
  "Cadillac": "cadillac.png",
  //Caterham
  "Caterham": "caterham.png",
  //Chevrolet
  "Chevrolet": "chevrolet.png",
  "MetalMoro AJR Chevrolet": "chevrolet.png",
  "MetalMoro AJR Gen2 Chevrolet": "chevrolet.png",
  "Camaro SafetyCar": "chevrolet.png",
  "ARC Camaro": "chevrolet.png",
  "Copa Montana": "chevrolet.png",
  //Dallara
  "Dallara": "dallara.png",
  //Dodge
  "Dodge": "dodge.png",
  //Ferrari
  "Ferrari": "ferrari.png",
  "Milano": "ferrari.png",
  //Fiat
  "Fiat": "fiat.png",
  "Copa Uno": "fiat.png",
  "Uno": "fiat.png",
  //Ford
  "Ford": "ford.png",
  "MetalMoro MRX Duratec P4": "ford.png",
  "MetalMoro MRX Duratec Turbo P3": "ford.png",
  "MetalMoro MRX Duratec Turbo P2": "ford.png",
  "Reynard 95i Ford-Cosworth": "ford.png",
  "Lola T95/00 Ford-Cosworth": "ford.png",
  "Reynard 98i Ford-Cosworth": "ford.png",
  "Lola T98/00 Ford-Cosworth": "ford.png",
  "Reynard 2Ki Ford-Cosworth": "ford.png",
  "Lola B2K00 Ford-Cosworth": "ford.png",
  "Swift 009c Ford-Cosworth": "ford.png",
  //Ginetta
  "Ginetta": "ginetta.png",
  //Honda
  "Honda": "honda.png",
  "MetalMoro MRX Honda P3": "honda.png",
  "MetalMoro AJR Honda": "honda.png",
  "MetalMoro AJR Gen2 Honda": "honda.png",
  "Reynard 95i Honda": "honda.png",
  "Reynard 98i Honda": "honda.png",
  "Reynard 2Ki Honda": "honda.png",
  //Iveco
  "Iveco": "iveco.png",
  //Judd
  "Judd": "judd.png",
  "MetalMoro AJR Judd": "judd.png",
  //Lamborghini
  "Lamborghini": "lamborghini.png",
  //Ligier
  "Ligier": "ligier.png",
  //Lola
  "Lola": "lola.png",
  //Lotus
  "Lotus": "lotus.png",
  //Man
  "Man": "man.truck.png",
  //Maseratti
  "Maserati": "maserati.png",
  //Mazda
  "Mazda": "mazda.png",
  //McLaren
  "McLaren": "mclaren.png",
  //MCR
  "MCR": "mcr.png",
  //Mercedes
  "Mercedes-AMG": "mercedes.png",
  "Mercedes-Benz": "mercedes.png",
  "Mercedes": "mercedes.png",
  "Reynard 95i Mercedes-Benz": "mercedes.png",
  "Lola T95/00 Mercedes-Benz": "mercedes.png",
  "Reynard 98i Mercedes-Benz": "mercedes.png",
  "Reynard 2Ki Mercedes-Benz": "mercedes.png",
  //Mini
  "MINI": "mini.png",
  //Mitsubishi
  "Mitsubishi": "mitsubishi.png",
  //Nissan
  "Nissan": "nissan.png",
  "MetalMoro AJR Nissan": "nissan.png",
  "MetalMoro AJR Gen2 Nissan": "nissan.png",
  //Oreca
  "Oreca": "oreca.png",
  //Peugeot
  "Peugeot": "peugeot.png",
  //Porsche
  "Porsche": "porsche.png",
  //Puma
  "Puma": "puma.png",
  //Radical
  "Radical": "radical.png",
  //Renault
  "Renault": "renault.png",
  //Roco
  "Roco": "roco.png",
  //Sigma
  "Sigma": "sigma.png",
  //Toyota
  "Toyota": "toyota.png",
  "Reynard 98i Toyota": "toyota.png",
  "Reynard 2Ki Toyota": "toyota.png",
  "Lola B2K00 Toyota": "toyota.png",
  //Ultima
  "Ultima": "ultima.png",
  //Volkswagen
  "Volkswagen": "volkswagen.png",
  "Gol": "volkswagen.png",
  "Fusca": "volkswagen.png",
  "Copa Fusca": "volkswagen.png",
  "Passat": "volkswagen.png",
  //volvo
  "Volvo": "volvo.png",
  "Vulkan": "volvo.png",
};